// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRzfmEpuLuzOYcOJLGrNP_6AepaKQChm0',
    appId: '1:689379082026:web:dc9b86b91edf1f0d75a853',
    messagingSenderId: '689379082026',
    projectId: 'enjaz-66bbe',
    authDomain: 'enjaz-66bbe.firebaseapp.com',
    storageBucket: 'enjaz-66bbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc4ij9GOhPaXZoCVOZxW2NwXV3qpbJMc8',
    appId: '1:689379082026:android:56487e12a2416e9375a853',
    messagingSenderId: '689379082026',
    projectId: 'enjaz-66bbe',
    storageBucket: 'enjaz-66bbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRpspocKvCE9ceDdehfxwuj74y2vN4heg',
    appId: '1:689379082026:ios:7c8d2cec99c0a81675a853',
    messagingSenderId: '689379082026',
    projectId: 'enjaz-66bbe',
    storageBucket: 'enjaz-66bbe.firebasestorage.app',
    iosBundleId: 'com.example.enjaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRpspocKvCE9ceDdehfxwuj74y2vN4heg',
    appId: '1:689379082026:ios:7c8d2cec99c0a81675a853',
    messagingSenderId: '689379082026',
    projectId: 'enjaz-66bbe',
    storageBucket: 'enjaz-66bbe.firebasestorage.app',
    iosBundleId: 'com.example.enjaz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRzfmEpuLuzOYcOJLGrNP_6AepaKQChm0',
    appId: '1:689379082026:web:41cee82024c1c4e575a853',
    messagingSenderId: '689379082026',
    projectId: 'enjaz-66bbe',
    authDomain: 'enjaz-66bbe.firebaseapp.com',
    storageBucket: 'enjaz-66bbe.firebasestorage.app',
  );
}
